FROM postgres

USER postgres
WORKDIR /app

COPY db/create_table.sql /docker-entrypoint-initdb.d/1_create.sql

COPY --chown=postgres:postgres ./docker/gateway/scripts/wait-for-postgres.sh ./bin/wait-for-postgres.sh
RUN chmod +x ./bin/wait-for-postgres.sh

EXPOSE 5432